# Generated by Django 4.2.6 on 2023-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_print_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
