# Generated by Django 4.2.6 on 2023-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='attachment',
            field=models.FileField(max_length=254, upload_to=''),
        ),
    ]
