# Generated by Django 4.2.6 on 2023-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_print_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=255),
        ),
    ]
