# Generated by Django 4.2.6 on 2023-12-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_print_attachment_alter_print_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
