# Generated by Django 4.2.6 on 2023-12-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_print_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pending'), ('impresso', 'Printed'), ('retirado', 'Withdrawn')], default='pending', max_length=255),
        ),
    ]
