# Generated by Django 4.2.6 on 2023-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_print_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('printed', 'Impresso'), ('withdrawn', 'Retirado')], default='pending', max_length=255),
        ),
    ]
