# Generated by Django 4.2.6 on 2023-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_print_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='is_sensible',
            field=models.BooleanField(default=False),
        ),
    ]
