# Generated by Django 4.2.6 on 2023-12-18 20:12

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_print_is_sensible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='attachment',
            field=models.FileField(max_length=254, upload_to=apps.core.models.get_file_path),
        ),
    ]
