# Generated by Django 4.2.6 on 2023-12-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_warning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='social_name',
            new_name='usual_name',
        ),
        migrations.AddField(
            model_name='user',
            name='google_classroom_email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_email',
            field=models.EmailField(default='email@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
