# Generated by Django 5.0 on 2023-12-19 10:59

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_warning_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='attachment',
            field=models.FileField(max_length=254, upload_to=apps.core.models.get_file_path, validators=[apps.core.models.file_size]),
        ),
    ]
