# Generated by Django 4.2.6 on 2023-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_print_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='print_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
